# Game variables
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 800
FPS = 180
# Colors
WHITE = (255, 255, 255)
LIGHT_GREY = (218, 218, 218)
BLACK = (0, 0, 0)
# Fonts
SLKSCREB = 'slkscreb.ttf'
PONG = 'pong_font.ttf'
# Ball variables
BALL_SIZE = 20
BALL_STARTING_POS = (SCREEN_WIDTH / 2 - BALL_SIZE / 2, SCREEN_HEIGHT / 2 - BALL_SIZE / 2)
# Paddle variables
PADDLE_SPEED = 1
PADDLE_HEIGHT = 100
PADDLE_WIDTH = 20
PADDLE_STARTING_Y = SCREEN_HEIGHT / 2 - PADDLE_HEIGHT / 2
PADDLE_STARTING_RIGHT_X = 970
PADDLE_STARTING_LEFT_X = 10
# Score variables
STARTING_SCORE = 0
SCORE_SIZE = 120
SCORE_STARTING_Y = 50
SCORE_STARTING_RIGHT_X = 650
SCORE_STARTING_LEFT_X = 290